services:
  e-com-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: e-com-server
    ports:
      - "4003:4000"
    env_file:
      - ./server/.env
    environment:
      SEED_ON_START: "true"
      SEED_CLEAR: "true"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: node dist/main.js
    # For development, you can use:
    # command: npm run start:dev
    networks:
      - shared-network

  e-com-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: e-com-client
    ports:
      - "4002:3000"
    env_file:
      - ./client/.env
    depends_on:
      - e-com-server

  e-com-admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: e-com-admin
    ports:
      - "4004:3000"
    env_file:
      - ./admin/.env
    depends_on:
      - e-com-server

networks:
  shared-network:
    external: true